use_frameworks!

def all_pods
  pod 'SDWebImageSwiftUI', :path => '../'
  pod 'SDWebImageWebPCoder'
  pod 'SDWebImageSVGCoder'
  pod 'SDWebImagePDFCoder'
end

target 'SDWebImageSwiftUIDemo' do
  platform :ios, '13.0'
  all_pods
end

target 'SDWebImageSwiftUIDemo-macOS' do
  platform :osx, '10.15'
  all_pods
end

target 'SDWebImageSwiftUIDemo-tvOS' do
  platform :tvos, '13.0'
  all_pods
end

target 'SDWebImageSwiftUIDemo-watchOS WatchKit Extension' do
  platform :watchos, '7.0'
  all_pods
end